import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { notoSansJP, notoSerifJP, tmpFont } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Hydrationの警告を抑制する
    <html lang="en" className="" suppressHydrationWarning>
      <body
        className={`${notoSerifJP.className} antialiased  dark:bg-contentBackGround dark:text-white`}
      >
        <ThemeProvider attribute="class" defaultTheme="systme" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
